version: "3"
services:

  openfact-web-console:
    image: openfact-web-console
    environment:
      - KEYCLOAK_PORT_8080_TCP_ADDR=192.168.1.30
      - KEYCLOAK_PORT_8080_TCP_PORT=8080
      - KEYCLOAK_REALM=openfact
      - KEYCLOAK_CLIENT_ID=openfact-web-console
      - OPENFACT_PORT_8080_TCP_ADDR=192.168.1.30
      - OPENFACT_PORT_8080_TCP_PORT=8081
    ports:
      - 4200:80
    networks:
      - frontend
    depends_on:
      - keycloak
      - openfact
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  openfact:
    image: openfact/openfact-postgres
    environment:
      - KEYCLOAK_PORT_8080_TCP_ADDR=keycloak
      - KEYCLOAK_PORT_8080_TCP_PORT=8080
      - DB_ADDR=openfactdb
      - DB_PORT=5432
    ports:
      - 8081:8080
    networks:
      - ubl
      - business
      - frontend
    depends_on:
      - openfactdb
      - keycloak
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  openfactdb:
    image: postgres:9.4
    environment:
      - POSTGRES_ROOT_PASSWORD=root_password
      - DB_DATABASE=openfact
      - DB_USERNAME=openfact
      - DB_PASSWORD=password
    volumes:
      - openfactdb-data:/var/lib/postgresql/data
    networks:
      - ubl
    deploy:
      placement:
        constraints: [node.role == manager]

  keycloak:
    image: openfact/keycloak-postgres
    environment:
      - DB_ADDR=keycloakdb
      - DB_PORT=5432
    ports:
      - 8080:8080
    networks:
      - sso
      - business
      - frontend
    depends_on:
      - keycloakdb
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  keycloakdb:
    image: postgres:9.4
    environment:
      - POSTGRES_ROOT_PASSWORD=root_password
      - DB_DATABASE=keycloak
      - DB_USERNAME=keycloak
      - DB_PASSWORD=password
    volumes:
      - keycloakdb-data:/var/lib/postgresql/data
    networks:
      - sso
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  sso:
  ubl:
  business:
  frontend:

volumes:
  keycloakdb-data:
  openfactdb-data:
